# -*- coding: utf-8 -*-
"""Salary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17hIgha4yMdwZhZmBeBqAJvW_r3d5cTu-
"""

# importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#reading the data
data=pd.read_csv('/content/salary.csv')
data

#printing them one by one
years=pd.DataFrame(data[['YearsExperience']])
salary=pd.DataFrame(data[['Salary']])
print(years)
print(salary)

#plotting the data
data.plot(kind='scatter',x='YearsExperience',y='Salary')
plt.show()

#Finding the co-relation
data.corr()
print('The corr btw the salary and years of experience :',(data['YearsExperience'].corr(data['Salary'])))

# Handling with model
from sklearn import linear_model
lr=linear_model.LinearRegression()
model=lr.fit(years,salary)
model.score(years,salary)

#printing model co=efficent
print('The co-eff is:',model.coef_)
print('The intercept is:',model.intercept_)

#plotting the data
data.plot(kind='scatter',x='YearsExperience',y='Salary')
plt.plot(years,model.predict(years),color='violet',linewidth=2)
plt.show()

#feeding new data and predicting
new_years=pd.DataFrame([5.2,7.8,9.4,12.2,2.87,1.5,2.5,3.5,4.5,])
new_salary=pd.DataFrame(model.predict(new_years))
new_data=[new_years,new_salary]
new_data=pd.DataFrame(new_data)
print('The Score of the model is:',model.score(new_years,new_salary))

#plotting the data
data.plot(kind='scatter',x='YearsExperience',y='Salary')
# regression line
plt.plot(years,model.predict(years),color='blue',linewidth=4)
#new data plotting
plt.scatter(new_years,new_salary,color='red')
#plotting predicted reg line
plt.plot(new_years,new_salary,color='red',linewidth=1)
plt.show()

